Python 3.7.0a2 (v3.7.0a2:f7ac4fe, Oct 17 2017, 17:06:29) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:/Users/DELL/AppData/Local/Programs/Python/Python37/my calulator ap.py 
enter the first number8
enter the second number9
************welcome to the calculator app************

please enter \ 
'+'  '-'  '*'  '/'*
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
multiplication is : 72
